### ISSUE TITLE
Ligature does not work

### ISSUE THREAD

**Issue by raismaulana** [Iosevka-Mayukai/Iosevka-Mayukai#4]
OS: Opensuse thumbelweed
Font Tried: Iosevka Mayukai Original v570, Iosevka Mayukai Sonata v570

But when i tried Fira Code Font, its is working.

**Comment by raismaulana** [comment]
I've tried to install in Windows 11 too, and the ligature does not work.
But again, Fira Code is working.
Am I missing something?

**Comment by raismaulana** [comment]
Again, i installed in Ubuntu too and the ligature does not work

**Comment by GulajavaMinistudio** [comment]
Thank you for submitting this issue. If you want to use ligature, you should enable it in your text editor setting, for example in VS Code, you should enable it Settings.

Here is my VS Code Settings to enable it. Add "editor.fontLigatures": true" in settings.json file.
![Screen Shot 2021-12-27 at 18 46 49](https://user-images.githubusercontent.com/11639412/147469072-205747ae-317c-48b3-a1ac-676193412f24.png)

And here the result , sample code with ligature enabled. You can see arrow function "=>" is using ligature.
![Screen Shot 2021-12-27 at 18 48 20](https://user-images.githubusercontent.com/11639412/147469199-a3b4d775-d6e2-4523-8ec1-b8f992d4035e.png)

**Comment by raismaulana** [comment]
![image](https://user-images.githubusercontent.com/22321111/147517729-46d40588-9e1b-4245-b0cb-df5968f8c97d.png)
![image](https://user-images.githubusercontent.com/22321111/147517781-a3568359-62d8-4f78-8463-90b5769ace66.png)
in my old device and iosevka mayukai old version (i forgot the number), this setting is work and if i use fira code, the ligatures is work too.

**Comment by GulajavaMinistudio** [comment]
After digging with font's build configuration , i found the issue. Ligature doesn't work because Nerd font patcher remove it. I suggest you to remove or delete Nerd Font variant that have been installed. It named "Iosevka Mayukai xxx Nerd Font Complete xxx" . Remove it from installation folder in your OS, for example in Ubuntu Linux, remove it from "./local/share/fonts" and run sudo fc-cache -f -v , and restart your code editor. 

It now work like a charm.
![Screenshot_2021-12-28_15-13-16](https://user-images.githubusercontent.com/11639412/147544526-3b7deb10-dd62-42ea-a67c-0a8e9275ce2c.png)

We will release the bug fix soon. 
But the work around is remove Nerd font variant that have been installed. Hope it works.

**Comment by raismaulana** [comment]
nice, just install the default (non nerd patched) and it works now thanks.
